// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzdx0cWrSssT_ZDOKSps0SbA1Q8mTvOHc',
    appId: '1:1057480710402:web:27333ba48f9509b6bf4a1b',
    messagingSenderId: '1057480710402',
    projectId: 'makuuygulama',
    authDomain: 'makuuygulama.firebaseapp.com',
    storageBucket: 'makuuygulama.appspot.com',
    measurementId: 'G-F1CCL1B3K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl_toqthX1y7hEP-QLpSKum5X8fmXQccA',
    appId: '1:1057480710402:android:ec68e171b391243dbf4a1b',
    messagingSenderId: '1057480710402',
    projectId: 'makuuygulama',
    storageBucket: 'makuuygulama.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpgwzm92tRsmXaNSGpNupXPcrJb2JAi9U',
    appId: '1:1057480710402:ios:d4e6b1216916eca1bf4a1b',
    messagingSenderId: '1057480710402',
    projectId: 'makuuygulama',
    storageBucket: 'makuuygulama.appspot.com',
    iosClientId: '1057480710402-rrodh18534oaj1kk34odp1itr6gjqira.apps.googleusercontent.com',
    iosBundleId: 'com.aom.makuuygulama',
  );
}
